### ISSUE TITLE
Add and serve development branch

### ISSUE THREAD

**Issue by mmontesanonyc** [nycehs/data-features#5]
Let's bring this repo in line with some other standards:
- create a development branch (create branch form main)
- serve that via github pages (via repository settings)

and then we'll adjust our workflow accordingly:
- features or fixes can be merged into development to be staged/previewed via githubpages
- things merged into main will be ready for primetime/deployment. 

@cgettings I assigned this issue to you - let me know if you have a hard time finding these functions.

**Comment by cgettings** [comment]
@mmontesanonyc re: #5:  `development` branch created, and GitHub pages site modified so it's built from that branch.

**Comment by mmontesanonyc** [comment]
Perfect. Thanks! 

Because of the old branch situation, we still have ``realtime.html`` on the main branch still - a small violation of our plan to have ``main`` only include things are deployable. So, I'll delete that for now, and we'll keep working on the working branch.

**Comment by cgettings** [comment]
Sounds good! Question: I closed this issue; is that alright, or should you have closed it after reviewing?

**Comment by mmontesanonyc** [comment]
I would say that for small stuff it's OK to close things quickly; for more substantive pull requests, it would be best to wait to merge the branch and then close the pull request after a second set of eyes have been on it.
