### ISSUE TITLE
Change README to show correct preview link

### ISSUE THREAD

**Issue by cgettings** [nycehs/data-features#6]
@mmontesanonyc I want to change the README to link to https://nycehs.github.io/data-features/AQHub/, rather than https://nycehs.github.io/AQHub_prototype/. My plan is to create a new branch, change the README, then submit a pull request to merge it into `development`. After that's approved, I'll submit another PR to merge the new branch into `main`. I'm not planning on touching `feature-rtaq`. Does this sound good?

**Comment by mmontesanonyc** [comment]
Yup, sounds perfect. Name that new branch ``hotfix-AQ-readme`` or something similar.
